### ISSUE TITLE
GraphQL error / Page not Found when trying to reach collective

### ISSUE THREAD

**Issue by Betree** [opencollective/frontend#549]
When trying to reach https://opencollective.com/paris this morning I get a `Not Found` error

> Preview

![Screenshot](https://user-images.githubusercontent.com/1556356/41765570-ba73ed20-7604-11e8-9695-83b1579d0db6.png)

> Console output

```
main-9bb7b75b93ab8f42ab5f.js:1 Unhandled (in react-apollo) Error: GraphQL error: The loader.load() function must be called with a value,but got: null.
    at new t (https://opencollective.com/_next/static/commons/main-9bb7b75b93ab8f42ab5f.js:1:1253405)
    at t.currentResult (https://opencollective.com/_next/static/commons/main-9bb7b75b93ab8f42ab5f.js:1:1255668)
    at s.dataForChild (https://opencollective.com/_next/static/commons/main-9bb7b75b93ab8f42ab5f.js:1:50448)
    at s.render (https://opencollective.com/_next/static/commons/main-9bb7b75b93ab8f42ab5f.js:1:51324)
    at Ba (https://opencollective.com/_next/static/commons/main-9bb7b75b93ab8f42ab5f.js:1:364438)
    at Ua (https://opencollective.com/_next/static/commons/main-9bb7b75b93ab8f42ab5f.js:1:370058)
    at _i (https://opencollective.com/_next/static/commons/main-9bb7b75b93ab8f42ab5f.js:1:379211)
    at Ii (https://opencollective.com/_next/static/commons/main-9bb7b75b93ab8f42ab5f.js:1:379521)
    at is (https://opencollective.com/_next/static/commons/main-9bb7b75b93ab8f42ab5f.js:1:383073)
    at ns (https://opencollective.com/_next/static/commons/main-9bb7b75b93ab8f42ab5f.js:1:382575)
```

**Comment by Betree** [comment]
It looks like the collective has moved to https://opencollective.com/opencollectiveparis

**Comment by Betree** [comment]
Collective does exist in DB as it still appears in search results:

![selection_520](https://user-images.githubusercontent.com/1556356/41768233-e73cb0ce-760b-11e8-8b08-d0ca1c5a96bd.png)

**Comment by HipsterBrown** [comment]
@Betree This has been fixed by https://github.com/opencollective/opencollective-api/pull/1344

Thanks for creating an issue and letting us know! 👍
