### ISSUE TITLE
Cannot set headers after they are sent to the client 

### ISSUE THREAD

**Issue by znarf** [opencollective/frontend#730]
```Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client ```

We have this error in production logs. We should find where it's coming from.

**Comment by znarf** [comment]
We actually more details:

```
Aug 31 08:58:23 oc-prod-frontend app/web.1: info: GET /robots.txt 304 1ms {"meta":{}} 
Aug 31 08:58:23 oc-prod-frontend app/web.1: { Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client 
Aug 31 08:58:23 oc-prod-frontend app/web.1:     at ServerResponse.setHeader (_http_outgoing.js:469:11) 
Aug 31 08:58:23 oc-prod-frontend app/web.1:     at Function.getInitialProps (/app/build/.next/server/bundles/pages/collective.js:21682:13) 
Aug 31 08:58:23 oc-prod-frontend app/web.1:     at Function._callee$ (/app/build/.next/server/bundles/pages/collective.js:378:31) 
Aug 31 08:58:23 oc-prod-frontend app/web.1:     at tryCatch (/app/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40) 
Aug 31 08:58:23 oc-prod-frontend app/web.1:     at Generator.invoke [as _invoke] (/app/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:296:22) 
Aug 31 08:58:23 oc-prod-frontend app/web.1:     at Generator.prototype.(anonymous function) [as next] (/app/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21) 
Aug 31 08:58:23 oc-prod-frontend app/web.1:     at step (/app/build/.next/server/bundles/pages/collective.js:186:30) 
Aug 31 08:58:23 oc-prod-frontend app/web.1:     at _next (/app/build/.next/server/bundles/pages/collective.js:201:9) 
Aug 31 08:58:23 oc-prod-frontend app/web.1:     at /app/build/.next/server/bundles/pages/collective.js:208:7 
Aug 31 08:58:23 oc-prod-frontend app/web.1:     at new Promise (<anonymous>) 
Aug 31 08:58:23 oc-prod-frontend app/web.1:     at Function.<anonymous> (/app/build/.next/server/bundles/pages/collective.js:181:12) 
```
